### ISSUE TITLE
Cannot start jupyther notebook 

### ISSUE THREAD

**Issue by eggcaker** [ligee/kotlin-jupyter#15]
After download and install kernel with ./gradlew install , start new notebook got error 

```
Starting server: KernelConfig(ports=[64057, 64053, 64056, 64055, 64054], transport=tcp, signatureScheme=hmac-sha256, signatureKey=9f641ffe-cea077832b193c4d7a1d72e4, pollingIntervalMillis=100, classpath=[/Users/eggcaker/.ipython/kernels/kotlin/kotlin-stdlib-1.2.21.jar, /Users/eggcaker/.ipython/kernels/kotlin/jupyter-lib-0.6.0.jar, /Users/eggcaker/.ipython/kernels/kotlin/annotations-13.0.jar])
[main] INFO ikotlin - start listening
Exception in thread "main" java.lang.NoClassDefFoundError: org/jetbrains/kotlin/com/intellij/openapi/diagnostic/Logger
	at uy.kohesive.keplin.kotlin.script.resolver.AnnotationTriggeredScriptDefinition.<clinit>(AnnotationTriggeredScriptDefinition.kt:70)
	at org.jetbrains.kotlin.jupyter.ReplForJupyter.<init>(repl.kt:22)
	at org.jetbrains.kotlin.jupyter.IkotlinKt.kernelServer(ikotlin.kt:62)
	at org.jetbrains.kotlin.jupyter.IkotlinKt.main(ikotlin.kt:41)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.kotlin.com.intellij.openapi.diagnostic.Logger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more
```

**Comment by holgerbrandl** [comment]
Same problem here. Is there a workaround until a proper fix is released?

**Comment by apatrida** [comment]
I'll check Keplin and the Jupyter-Kotlin to see where the breaking is, and where that reference is coming from.

**Comment by davidsands** [comment]
Could it be jetbrains moved the intellij.openapi.diagnostic.Logger class? 

In the keplin source:
keplin-core/src/main/kotlin/uy/kohesive/keplin/kotlin/script/resolver/AnnotationTriggeredScriptDefinition.kt
   ...
   import org.jetbrains.kotlin.com.intellij.openapi.diagnostic.Logger
   ...

Exception in thread "main" java.lang.NoClassDefFoundError:
          org/jetbrains/kotlin/com/intellij/openapi/diagnostic/Logger

Current location of the class:
   found in kotlin-compiler-1.2.21.jar
          com/intellij/openapi/diagnostic/Logger.class 

I don't have enough experience to know how to fix this, if it is indeed the problem.

**Comment by apatrida** [comment]
I see the mismatch in compiler libraries, so working to fix that now.

**Comment by apatrida** [comment]
Can someone check master now and see if you still have the issue?

**Comment by davidsands** [comment]
It's fixed here. Muchas gracias!

**Comment by holgerbrandl** [comment]
Same here. Herzlichen Dank!

**Comment by eggcaker** [comment]
works. 👍
