### ISSUE TITLE
The kernel crashes after running println twice

### ISSUE THREAD

**Issue by oroszgy** [ligee/kotlin-jupyter#4]
When I am running this

``` kotlin
println("hello")
```

then going back to the row, tun this again, the kernel just crashes with the following error:

``` kotlin
[main] ERROR ikotlin - exception running kernel with args: "/Users/gyorgyorosz/Library/Jupyter/runtime/kernel-5687fb6d-e87f-46f6-968b-237817dbfa13.json, -cp=/Users/gyorgyorosz/.ipython/kernels/kotlin/lib/kotlin-stdlib-1.1.0-dev-1920.jar:/Users/gyorgyorosz/.ipython/kernels/kotlin/lib/jupyter-lib-0.2.0.jar:/Users/gyorgyorosz/.ipython/kernels/kotlin/lib/kotlin-runtime-1.1.0-dev-1920.jar"
java.lang.IllegalStateException: Rewrite at key Line1
        at org.jetbrains.kotlin.cli.jvm.repl.ReplClassLoader.addClass(ReplClassLoader.java:51)
        at org.jetbrains.kotlin.jupyter.ReplForJupyter.eval(repl.kt:169)
        at org.jetbrains.kotlin.jupyter.IkotlinKt.shellMessagesHandler(ikotlin.kt:141)
        at org.jetbrains.kotlin.jupyter.IkotlinKt.kernelServer(ikotlin.kt:87)
        at org.jetbrains.kotlin.jupyter.IkotlinKt.main(ikotlin.kt:43)
Exception in thread "Thread-0" org.zeromq.ZMQException: Errno 156384765 : Context was terminated
        at org.zeromq.ZMQ$Socket.mayRaise(ZMQ.java:1456)
        at org.zeromq.ZMQ$Socket.recv(ZMQ.java:1365)
        at org.jetbrains.kotlin.jupyter.IkotlinKt$kernelServer$$inlined$use$lambda$1.invoke(ikotlin.kt:182)
        at org.jetbrains.kotlin.jupyter.IkotlinKt$kernelServer$$inlined$use$lambda$1.invoke(ikotlin.kt)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:18)
```

**Comment by happy15** [comment]
+1 encountered the same error

and instead of printing "hello" it just returned a "Ok" when println("hello") once

**Comment by apatrida** [comment]
@ligee please close, fixed in previous PR
